### ISSUE TITLE
Tag for setting overwritten methods

### ISSUE THREAD

**Issue by erdlet** [mvc-toolbox/mvc-toolbox#31]
To ease the form method overwrite, a set of tags like `<t:patch/>` may be helpful.

## TODOs

As discussed below, the following tasks need to be done to close this issue:

- [ ] Add a tag `<t:methodPut>` which creates the hidden input field for a `PUT` request
- [ ] Add a tag `<t:methodPatch>` which creates the hidden input field for a `PATCH` request
- [ ] Add a tag `<t:methodDelete>` which creates the hidden input field for a `DELETE` request

**Comment by chkal** [comment]
I wonder if this is explicit enough. What about `<t:method value="PATCH"/>` instead? Less typesafe, but more explicit. Not sure to be honest which I prefer. ;-)

**Comment by erdlet** [comment]
Good point. Or maybe a more explicit naming like `t:method-patch`🤔 My intention is at least to remove the error prone string

**Comment by chkal** [comment]
Yes, maybe `<t:method-patch/>` is the best of both worlds? What is best practice for JSP tags? Camel-case or kebab-case?

**Comment by erdlet** [comment]
I'll have a look into existing taglibs. Not sure if there's a convention

**Comment by chkal** [comment]
It looks like JSTL and Jakarta Faces use camel-case:

https://jakarta.ee/specifications/tags/3.0/tagdocs/
https://jakarta.ee/specifications/faces/3.0/vdldoc/

**Comment by erdlet** [comment]
Then we'll use camelCase. I don't have personal preferences on this topic

**Comment by erdlet** [comment]
So I'd add the following tags:

- `<t:methodPut>`
- `<t:methodPatch>`
- `<t:methodDelete>`

Also they get an additional parameter which can be used to pass an alternative name for the hidden field. It seems that I forgot to add a convenience access method to the `MvcContext` in MVC 2.1, so there may be some workaround necessary. I'll add an issue to the spec to get the overwritten hidden field name via `MvcContext`.
